version: "3.7"

services:
  app:
    image: todo-app:latest
    ports:
    - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/todo
      - SPRING_DATASOURCE_USERNAME=todo
      - SPRING_DATASOURCE_PASSWORD=todo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SERVER_PORT=8080

  postgres:
    image: postgres:9.4
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    volumes:
      - todo-pgsql-data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  todo-pgsql-data: