DROP TABLE IF EXISTS ToDo;

CREATE TABLE ToDo (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Description VARCHAR(500) NULL,
    Status VARCHAR (20) NOT NULL,
    CreatedDt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedDt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);