CREATE TABLE ToDo(
    ID SERIAL PRIMARY KEY,
    Title VARCHAR NOT NULL,
    IsComplete BOOLEAN NOT NULL DEFAULT FALSE,
    Created_at TIMESTAMP DEFAULT NOW(),
    Updated_at TIMESTAMP DEFAULT NOW()
)